// Guild War Player Data - Maximum 30 players per guild
// When Wind Meets - Guild vs Guild
const members = [
    { id: 1, name: "Player01", role: "Tank", team: "FrontLine" },
    { id: 2, name: "Player02", role: "DPS", team: "FrontLine" },
    { id: 3, name: "Player03", role: "DPS", team: "FrontLine" },
    { id: 4, name: "Player04", role: "Tank", team: "FrontLine" },
    { id: 5, name: "Player05", role: "Support", team: "FrontLine" },
    { id: 6, name: "Player06", role: "DPS", team: "Jungle" },
    { id: 7, name: "Player07", role: "Tank", team: "Jungle" },
    { id: 8, name: "Player08", role: "DPS", team: "Jungle" },
    { id: 9, name: "Player09", role: "Support", team: "Jungle" },
    { id: 10, name: "Player10", role: "DPS", team: "Jungle" },
    { id: 11, name: "Player11", role: "Tank", team: "Defence 1" },
    { id: 12, name: "Player12", role: "DPS", team: "Defence 1" },
    { id: 13, name: "Player13", role: "Healer", team: "Defence 1" },
    { id: 14, name: "Player14", role: "Support", team: "Defence 1" },
    { id: 15, name: "Player15", role: "DPS", team: "Defence 1" },
    { id: 16, name: "Player16", role: "Tank", team: "Defence 2" },
    { id: 17, name: "Player17", role: "DPS", team: "Defence 2" },
    { id: 18, name: "Player18", role: "Healer", team: "Defence 2" },
    { id: 19, name: "Player19", role: "Support", team: "Defence 2" },
    { id: 20, name: "Player20", role: "DPS", team: "Defence 2" },
    { id: 21, name: "Player21", role: "DPS", team: "Backline 1" },
    { id: 22, name: "Player22", role: "Healer", team: "Backline 1" },
    { id: 23, name: "Player23", role: "Support", team: "Backline 1" },
    { id: 24, name: "Player24", role: "DPS", team: "Backline 1" },
    { id: 25, name: "Player25", role: "Healer", team: "Backline 1" },
    { id: 26, name: "Player26", role: "DPS", team: "Backline 2" },
    { id: 27, name: "Player27", role: "Healer", team: "Backline 2" },
    { id: 28, name: "Player28", role: "Support", team: "Backline 2" },
    { id: 29, name: "Player29", role: "DPS", team: "Backline 2" },
    { id: 30, name: "Player30", role: "Support", team: "Backline 2" }
];
